### ISSUE TITLE
RTX 3080: Training MobileViT

### ISSUE THREAD

**Issue by khawar-islam** [godhj93/MobileViT#1]
Hello @godhj93, 

I am training MobileViT using your repository and i am unable to find the TensorFlow GPU version for my system. 
Do you have an idea?

System: Ubuntu 20.4.04
Python: 3.9.7
CUDA: 11.6

**Comment by godhj93** [comment]
Hi @khawar-islam 
I think the CUDA version what you are using now is not compatible tensorflow.
I recommend you to check this [table](https://www.tensorflow.org/install/source#gpu).
My environment settings are:
System: Ubuntu20.04
Python: 3.9
CUDA: 11.2
cuDNN: 8.1
Tensorflow: 2.8
